### ISSUE TITLE
Programmatically accessing mocks leads to errors

### ISSUE THREAD

**Issue by vrdyquest** [lwsjs/local-web-server#105]
I was able to start the lws mocks programmatically with help of node when I run the following script standalone

```
const LocalWebServer = require("local-web-server");
const localWebServer = new LocalWebServer();
const server = localWebServer.listen({
    port: 8050,
    directory: "mocks",
    mocks: ["mocks/mockfile"]
});
// server with listening websocket now ready on port 8050

const sleep = (milliseconds) => {
    return new Promise(resolve => setTimeout(resolve, milliseconds))
};
// Stop listening when/if server is no longer needed

sleep(50000).then(() => {
    //do stuff
    server.close();
});
```

When I try to call the same in before() and after hooks in mocha for unittesting purposes, I get the following error. 

Here's what I have as a hook file

```
const LocalWebServer = require('local-web-server');
const localWebServer = new LocalWebServer();
let server;
// server with listening websocket now ready on port 8050

const sleep = (milliseconds) => {
    return new Promise(resolve => setTimeout(resolve, milliseconds))
};
// Stop listening when/if server is no longer needed
export const before = function() {
    // runs before all tests in this block
    server = localWebServer.listen({
        port: 8050,
        directory: 'test/mocks',
        mocks: ["test/mockfile.js"]
    });

};
export const after = function (done) {
    sleep(10).then(() => {
        //do stuff
        server.close(done);
    });
};

```
and the above consts imported into test file like this

```
import {before, after} from "../start-mocks";
describe("affix-retriever", function () {
before(function () {
        before();
    });

describe("......");

after(function () {
        after();
    });

```
and this function call of before and after leads me to following errors

```
/Users/vrdy/projects/prm//test/mocks/mockfile.js:17
        return _possibleConstructorReturn(this, (MockSuggest.__proto__ || Object.getPrototypeOf(MockSuggest)).apply(this, arguments));
                                                                                                              ^

TypeError: Class constructor MockBase cannot be invoked without 'new'
    at new MockSuggest (/Users/vreddy/projects/webcomponents/name-studio/test/mocks/suggest.js:1:18)
    at mocks.map.mockModule (/Users/vreddy/projects/webcomponents/name-studio/node_modules/lws-mock-response/index.js:36:22)
    at Array.map (<anonymous>)
    at MockResponse.middleware (/Users/vreddy/projects/webcomponents/name-studio/node_modules/lws-mock-response/index.js:33:10)
    at filter.map.mw (/Users/vreddy/projects/webcomponents/name-studio/node_modules/lws/lib/stack.js:21:21)
    at Stack.map (<anonymous>)

```

Has anyone seen this as a problem reported by someone? Appreciate your input

Thanks

**Comment by 75lb** [comment]
I suspect this bug lies somewhere in your code, not in local-web-server. If you send me a reproduction case (some failing code i can run and debug) i'll take a look at this for you.

**Comment by 75lb** [comment]
will re-open once i receive a reproduction case.
