### ISSUE TITLE
Middleware error EADF and ECONNRESET

### ISSUE THREAD

**Issue by kumargauravin** [lwsjs/local-web-server#109]
We are getting this error in Production. Please indicate what we can be doing wrong.
We are using a mock JS for two API static response but those are working.

23:16:15: Middleware error
Error: EBADF: bad file descriptor, read
20:23:04: Middleware error
Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
16:21:14: Middleware error
Error: This socket is closed
    at Socket._writeGeneric (net.js:726:18)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at Socket.Writable.end (_stream_writable.js:553:10)
    at Socket.end (net.js:496:31)
    at Server.server.on (/usr/src/app/node_modules/lws/index.js:242:24)
    at emitTwo (events.js:126:13)
20:20:13: Middleware error
Error: This socket is closed
    at Socket._writeGeneric (net.js:726:18)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at Socket.Writable.end (_stream_writable.js:553:10)
    at Socket.end (net.js:496:31)
    at Server.server.on (/usr/src/app/node_modules/lws/index.js:242:24)
    at emitTwo (events.js:126:13)

**Comment by 75lb** [comment]
This is an OS-level issue.. Linux operating systems have a limit on the number of file descriptors that may be open at any one time, see the `ulimit` command: https://docs.oracle.com/cd/E19623-01/820-6168/file-descriptor-requirements.html.

Try researching "bad file descriptor".. this is not an issue with local-web-server itself but something more low-level.
