### ISSUE TITLE
Middleware error > Error: write ECONNRESET

### ISSUE THREAD

**Issue by larryw3i** [lwsjs/local-web-server#142]
**These issues only appears on the browser of phone**
``` 
xx:xx:xx AM: Middleware error
Error: write ECONNRESET
    at afterWriteDispatched (internal/stream_base_commons.js:149:25)
    at writeGeneric (internal/stream_base_commons.js:140:3)
    at Socket._writeGeneric (net.js:776:11)
    at Socket._write (net.js:788:8)
    at doWrite (_stream_writable.js:435:12)
    at clearBuffer (_stream_writable.js:574:7)
    at Socket.Writable.uncork (_stream_writable.js:329:7)
    at connectionCorkNT (_http_outgoing.js:656:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
------------------------------------------------------------------------------------------------------
Another case is that :
```
xx:xx:xx AM: Middleware error
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200:27)
``` 
**It is work well when I use the browser of my laptop**

**Comment by 75lb** [comment]
I can't reproduce this issue - it works fine on my phone. 

I'm not convinced this is a issue with local-web-server, it sounds more like an issue with node, your phone browser or OS. 

Please provide a concrete reproduction case - something I can run and consistently see fail.

**Comment by larryw3i** [comment]
Ok, I think it should only appear on individual mobile browsers, thank you.
