### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by duzenko** [lwsjs/local-web-server#182]
Node.js 11, Windows 10
```
$ ws
C:\Users\a\AppData\Roaming\npm\node_modules\local-web-server\bin\cli.mjs:2
import WsCli from '../lib/cli-app.mjs'
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by 75lb** [comment]
For Node v11 support, please use v3 of local-web-server: `npm install --global local-web-server@^3`

The latest version of this tool requires Node.js v12.20 or above.
