### ISSUE TITLE
HTTPS using own certificate - TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by radum** [lwsjs/local-web-server#69]
Hello

When I try to use my own certificare like this

```
ws -p 4243 --key ~/personal/ssl/local.dev.key --cert ~/personal/ssl/local.dev.crt
```

It fails with:

```
TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at HttpsServerFactory.create (/Volumes/Data/Users/radmicu/.nvm/versions/node/v8.1.3/lib/node_modules/local-web-server/node_modules/lws/lib/server-factory-https.js:14:30)
    at Lws.createServer (/Volumes/Data/Users/radmicu/.nvm/versions/node/v8.1.3/lib/node_modules/local-web-server/node_modules/lws/lib/lws.js:130:20)
    at Lws.listen (/Volumes/Data/Users/radmicu/.nvm/versions/node/v8.1.3/lib/node_modules/local-web-server/node_modules/lws/lib/lws.js:47:25)
    at WsServe.execute (/Volumes/Data/Users/radmicu/.nvm/versions/node/v8.1.3/lib/node_modules/local-web-server/node_modules/lws/lib/command/serve.js:276:26)
    at WsServe.execute (/Volumes/Data/Users/radmicu/.nvm/versions/node/v8.1.3/lib/node_modules/local-web-server/lib/command/serve.js:16:18)
    at Map.start (/Volumes/Data/Users/radmicu/.nvm/versions/node/v8.1.3/lib/node_modules/local-web-server/node_modules/cli-commands/index.js:26:18)
    at WsCliApp.start (/Volumes/Data/Users/radmicu/.nvm/versions/node/v8.1.3/lib/node_modules/local-web-server/node_modules/lws/lib/cli-app.js:11:34)
    at Function.run (/Volumes/Data/Users/radmicu/.nvm/versions/node/v8.1.3/lib/node_modules/local-web-server/node_modules/lws/lib/cli-app.js:23:21)
```

The previous version worked just fine :|

**Comment by 75lb** [comment]
fixed and released in lws v1.1.2 and local-web-server v2.2.2.

Thanks and let me know if you find anything else 👍
