### ISSUE TITLE
Middleware error: BadRequestError: Malicious Path problem

### ISSUE THREAD

**Issue by hungtruongquoc** [lwsjs/local-web-server#77]
I ran 'ws -s index.html' and I got the error: 

BadRequestError: Malicious Path
    at resolvePath (/usr/lib/node_modules/local-web-server/node_modules/resolve-path/index.js:77:11)
    at send (/usr/lib/node_modules/local-web-server/node_modules/koa-send/index.js:68:10)
    at serve (/usr/lib/node_modules/local-web-server/node_modules/koa-static/index.js:44:24)
    at dispatch (/usr/lib/node_modules/local-web-server/node_modules/koa-compose/index.js:42:32)
    at next (/usr/lib/node_modules/local-web-server/node_modules/koa-compose/index.js:43:18)
    at Object._.get (/usr/lib/node_modules/local-web-server/node_modules/lws-spa/index.js:35:18)
    at /usr/lib/node_modules/local-web-server/node_modules/koa-route/index.js:39:44
    at dispatch (/usr/lib/node_modules/local-web-server/node_modules/koa-compose/index.js:42:32)
    at next (/usr/lib/node_modules/local-web-server/node_modules/koa-compose/index.js:43:18)
    at etag (/usr/lib/node_modules/local-web-server/node_modules/koa-etag/index.js:26:12)

This is the detail of the request

![image](https://user-images.githubusercontent.com/1299962/32902099-1a60effc-cab7-11e7-8bd4-0d76d34ec36b.png)

The local-web-server was an internal server and the requests redirected from a Apache proxy server. The following rules are used for the proxy

 ProxyPass "/static" "http://localhost:8000/"
#ProxyPassReverse "/static/" "http://localhost:8000"

**Comment by 75lb** [comment]
This is not a local-web-server issue. [See here for common Malicious Path causes](https://github.com/koajs/send/issues/51).

Try running ws with the verbose flag to get more insight: 

```
$ ws --verbose
```

**Comment by 75lb** [comment]
also, see the [resolve-path README](https://github.com/pillarjs/resolve-path) for more info regarding which paths are considered "malicious".

**Comment by hungtruongquoc** [comment]
Thanks for quick reply and details :)
