### ISSUE TITLE
spa and stack not working together in command line

### ISSUE THREAD

**Issue by maxorlovsky** [lwsjs/local-web-server#92]
Trying to run --spa with --stack from command line will return an error
```
$ node_modules/.bin/ws --spa --stack redirect-everything.js
UNKNOWN_OPTION: Unknown option: --spa
    at commandLineArgs (/var/www/sfww/node_modules/command-line-args/index.js:59:21)
    at WsServe.getOptions (/var/www/sfww/node_modules/lws/lib/command/serve.js:260:18)
    at WsServe.execute (/var/www/sfww/node_modules/lws/lib/command/serve.js:271:20)
    at WsServe.execute (/var/www/sfww/node_modules/local-web-server/lib/command/serve.js:16:18)
    at Map.start (/var/www/sfww/node_modules/cli-commands/index.js:26:18)
    at WsCliApp.start (/var/www/sfww/node_modules/lws/lib/cli-app.js:11:34)
    at Function.run (/var/www/sfww/node_modules/lws/lib/cli-app.js:23:21)
    at Object.<anonymous> (/var/www/sfww/node_modules/local-web-server/bin/cli.js:12:29)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
```

**Comment by 75lb** [comment]
`--spa` is an option defined by the `lws-spa` middleware. If you run `ws --config` in a folder without `lws.config.js` you will see `'Spa'` (exported by the module `lws-spa`) is included in the default middleware stack. 

If you remove `lws-spa` from the stack (by supplying your own `--stack` which does not include it), you'll lose all spa options including `--spa`.
